In [12]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,f1_score,confusion_matrix,classification_report
from sklearn.naive_bayes import GaussianNB
data=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/iris.csv')

print(data.head(10))

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa


In [18]:
x=data.drop('Species',axis=1)
y=data['Species']

label=LabelEncoder()
y=label.fit_transform(y)

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

model=GaussianNB()
model.fit(x_train,y_train)

model.fit(x_train,y_train)
y_pred = model.predict(x_test)
accuracy = accuracy_score(y_pred, y_test)
f1 = f1_score(y_pred, y_test, average="weighted")
conf_matrix=confusion_matrix(y_pred,y_test,labels=[0,1,2])

print("Accuracy :",accuracy)
print("F1 Score :",f1)
print("Confusion Matrix :\n",conf_matrix)

Accuracy : 0.9666666666666667
F1 Score : 0.9675645342312009
Confusion Matrix :
 [[11  0  0]
 [ 0 13  1]
 [ 0  0  5]]


In [22]:
from sklearn.datasets import load_iris
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score,classification_report

iris = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/iris.csv')

X = iris.drop('Species',axis=1)
y = iris['Species']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

model = GaussianNB()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

conf_matrix = confusion_matrix(y_test, y_pred)

accuracy = accuracy_score(y_test, y_pred)
error_rate = 1 - accuracy
precision = precision_score(y_test, y_pred, average='macro')
recall = recall_score(y_test, y_pred, average='macro')
f1 = f1_score(y_test, y_pred, average='macro')
classification_rep = classification_report(y_test, y_pred, target_names=iris['Species'].unique())

print("Confusion Matrix:\n", conf_matrix)
print("\nAccuracy:", accuracy)
print("Error Rate:", error_rate)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)


Confusion Matrix:
 [[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]

Accuracy: 0.9777777777777777
Error Rate: 0.022222222222222254
Precision: 0.9761904761904763
Recall: 0.9743589743589745
F1 Score: 0.974320987654321
